### ISSUE TITLE
Handle special TryAPL replies with backspaces

### ISSUE THREAD

**Issue by RojerGS** [RojerGS/TryAPL-Bot#2]
According to https://chat.stackexchange.com/transcript/message/58424796#58424796,
if TryAPL replies with a result that starts with a backspace, then it is a "special" reply that was tagged with the backspace so that the frontend of TryAPL could act in a special way. When that is the reply we get back, then the actual result we care about is the last item of the "backspace"-separated result.

It could raise the issue of "what if the expression typed actually returns a legit, purposeful backspace as the first character", but TryAPL returns the "picture" of the result, not the true result, so no legit result will ever start with backspace.

**Comment by abrudz** [comment]
In fact, when you detect a help tag, simply respond with a tweet that has the returned URL. No need to say "Run it…" or include a picture.

**Comment by RojerGS** [comment]
Therefore, should I detect backspace-tags and then, if it is a help tag, special-case that as well?

**Comment by abrudz** [comment]
What do you mean by "as well"? There's only one thing to special case here:
If the result from the TryAPL request comes back with a text that begins with a backspace, remove the tag, and post the rest of the text as a tweet by it self, without the "Run it online" lede or adding a picture.

**Comment by RojerGS** [comment]
You are assuming, then, that the only results that will ever start with backspace are help results? Or is it a known fact that that is how it is going to work?

**Comment by abrudz** [comment]
Good point. Better to check if the response begins with BShelpBS.
